'use client';

import { Share2, Download } from 'lucide-react';
import { IncidentRecord } from '../types';

interface ShareButtonProps {
  incident: IncidentRecord;
  variant?: 'enabled' | 'disabled';
}

export const ShareButton = ({ incident, variant = 'enabled' }: ShareButtonProps) => {
  const generateSummary = (record: IncidentRecord): string => {
    const date = record.timestamp.toLocaleDateString();
    const time = record.timestamp.toLocaleTimeString();
    
    return `
🚨 INCIDENT REPORT 🚨

Date: ${date}
Time: ${time}
Location: ${record.location.latitude}, ${record.location.longitude}

KNOW YOUR RIGHTS:
• Right to remain silent
• Right to refuse searches  
• Right to an attorney

Important: This incident has been recorded.
For legal assistance, contact your attorney immediately.

Generated by KnowYourRights Card
    `.trim();
  };

  const handleShare = async () => {
    if (variant === 'disabled') return;

    const summary = generateSummary(incident);

    try {
      if (navigator.share) {
        await navigator.share({
          title: 'Incident Report',
          text: summary,
        });
      } else {
        // Fallback: copy to clipboard
        await navigator.clipboard.writeText(summary);
        alert('Incident summary copied to clipboard');
      }
    } catch (error) {
      console.error('Error sharing:', error);
      // Fallback: copy to clipboard
      try {
        await navigator.clipboard.writeText(summary);
        alert('Incident summary copied to clipboard');
      } catch (clipboardError) {
        console.error('Clipboard error:', clipboardError);
      }
    }
  };

  const handleDownload = () => {
    if (!incident.audioBlob) return;

    const url = URL.createObjectURL(incident.audioBlob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `incident-${incident.timestamp.getTime()}.webm`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex space-x-3">
      <button
        onClick={handleShare}
        disabled={variant === 'disabled'}
        className={`
          flex-1 flex items-center justify-center space-x-2 px-4 py-3 rounded-md font-medium transition-all
          ${variant === 'disabled'
            ? 'bg-gray-600 text-gray-400 cursor-not-allowed'
            : 'btn-primary'
          }
        `}
      >
        <Share2 className="w-4 h-4" />
        <span>Share Summary</span>
      </button>

      {incident.audioBlob && (
        <button
          onClick={handleDownload}
          className="px-4 py-3 bg-surface border border-white/10 rounded-md hover:bg-white/5 transition-colors"
        >
          <Download className="w-4 h-4" />
        </button>
      )}
    </div>
  );
};
